platform :ios, '12.0'

use_frameworks!

target 'IconTextField_Example' do
  pod 'IconTextField2', :path => '../'
  pod 'SnapKit'

  target 'IconTextField_Tests' do
    inherit! :search_paths

    
  end
end
